spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/resttemplate
    username: root
    password: hunil@3751
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8000
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      show_sql: true
      format_sql: true
    logging.level:
      org.hibernate.SQL: debug